name: Build and Release PDFs

on:
  push:
    branches:
      - main
      - 'languages/*'
  pull_request:
    branches:
      - main
      - 'languages/*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Typst
        uses: docker://ghcr.io/typst/typst:latest
        with:
          args: c cv.typ

      - name: Determine artifact name
        id: artifact_name
        run: |
          if [[ "${{ github.ref_name }}" == languages/* ]]; then
            # Remove 'languages/' prefix
            BRANCH_NAME="${{ github.ref_name }}"
            ARTIFACT_NAME="cv_${BRANCH_NAME#languages/}.pdf"
          else
            ARTIFACT_NAME="cv_${{ github.ref_name }}.pdf"
          fi
          echo "name=$ARTIFACT_NAME" >> $GITHUB_ENV

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.name }}
          path: cv.pdf
