name: Build and Release PDFs

on:
  push:
    branches:
      - main
      - 'languages/*'
  pull_request:
    branches:
      - main
      - 'languages/*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Typst
        uses: docker://ghcr.io/typst/typst:latest
        with:
          args: c cv.typ

      - name: Determine artifact name
        id: artifact_name
        run: |
          if [[ "${{ github.ref_name }}" == languages/* ]]; then
            echo "name=cv_${{ github.ref_name }#languages/}.pdf" >> $GITHUB_ENV
          else
            echo "name=cv_${{ github.ref_name }}.pdf" >> $GITHUB_ENV
          fi

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.name }}
          path: cv.pdf
